# Read PODNet results

In [30]:
import json
import numpy as np
import os

In [31]:
repo_list = os.listdir('./results/podnet')
repo_list.sort()
repo_list

['20230428-1347_podnet_nme_cifar100_5steps',
 '20230428-2006_podnet_nme_cifar100_5steps_pretrained',
 '20230501-0551_podnet_nme_cifar100_10steps',
 '20230501-1351_podnet_nme_cifar100_10steps_pretrained',
 '20230501-2145_podnet_nme_cifar100_25steps',
 '20230502-1204_podnet_nme_cifar100_25steps_pretrained',
 '20230503-0247_podnet_nme_cifar100_50steps',
 '20230504-0220_podnet_nme_cifar100_50steps_pretrained',
 '20230505-0301_cifar_cnn_inc_10',
 '20230505-0831_cifar_cnn_inc_10_pretrained',
 '20230505-1402_cifar_cnn_inc_5',
 '20230505-2037_cifar_cnn_inc_5_pretrained',
 '20230506-0318_cifar_cnn_inc_2',
 '20230506-1323_cifar_cnn_inc_2_pretrained',
 '20230506-2323_cifar_cnn_inc_1',
 '20230507-1600_cifar_cnn_inc_1_pretrained']

In [32]:
inc_list = [6,6,11,11,26,26,51,51,6,6,11,11,26,26,51,51]

In [33]:
def get_avg_acc(repo,inc):
    accs = []
    for seed in range(3):
        with open(repo+'/run_'+str(seed)+'_.json', 'r') as f:
            json_data = json.load(f)

        accs.append(json_data['results'][-1]['incremental_accuracy'])

    accuracy = np.array(accs) * 100
    return accuracy, accuracy.mean(axis=0), accuracy.std(axis=0)

In [34]:
for i in range(16):
    accs, mean, std = get_avg_acc('./results/podnet/'+repo_list[i],inc_list[i])
    print(repo_list[i])
    print(accs)
    print()

20230428-1347_podnet_nme_cifar100_5steps
[61.48333333 60.26666667 63.06666667]

20230428-2006_podnet_nme_cifar100_5steps_pretrained
[63.31666667 61.6        64.35      ]

20230501-0551_podnet_nme_cifar100_10steps
[59.14545455 57.89090909 60.86363636]

20230501-1351_podnet_nme_cifar100_10steps_pretrained
[61.68181818 59.39090909 62.29090909]

20230501-2145_podnet_nme_cifar100_25steps
[55.40769231 54.06153846 57.01153846]

20230502-1204_podnet_nme_cifar100_25steps_pretrained
[57.33461538 56.07307692 59.33076923]

20230503-0247_podnet_nme_cifar100_50steps
[50.79215686 49.00980392 52.71764706]

20230504-0220_podnet_nme_cifar100_50steps_pretrained
[53.1627451  51.34117647 55.28235294]

20230505-0301_cifar_cnn_inc_10
[58.26666667 57.23333333 59.7       ]

20230505-0831_cifar_cnn_inc_10_pretrained
[61.16666667 60.43333333 62.26666667]

20230505-1402_cifar_cnn_inc_5
[55.29090909 54.71818182 57.28181818]

20230505-2037_cifar_cnn_inc_5_pretrained
[58.         57.63636364 59.51818182]

20230506-0

In [6]:
def get_acc(repo,inc):
    accs = []
    for seed in range(3):
        with open(repo+'/run_'+str(seed)+'_.json', 'r') as f:
            json_data = json.load(f)

        acc = []
        for i in range(inc):
            acc.append(json_data['results'][i]['accuracy']['total'])

        accs.append(acc)

    accuracy = np.array(accs) * 100
    return accuracy.mean(axis=0), accuracy.std(axis=0)

In [4]:
non_mean, non_std = get_acc('./results/podnet/20230428-1347_podnet_nme_cifar100_5steps',6)
print(non_mean)
print(non_std)

[73.93333333 68.13333333 62.5        58.8        54.96666667 51.3       ]
[2.24845626 1.59234279 0.64807407 0.65319726 1.25521136 0.82865353]


In [16]:
for i in range(16):
    mean, std = get_acc('./results/podnet/'+repo_list[i],inc_list[i])
    print(mean)
    print(std)

[73.93333333 68.13333333 62.5        58.8        54.96666667 51.3       ]
[2.24845626 1.59234279 0.64807407 0.65319726 1.25521136 0.82865353]
[75.36666667 69.46666667 63.73333333 60.13333333 56.66666667 53.16666667]
[2.20050499 1.46135401 0.57927157 0.81785628 1.24988888 0.77172246]
[73.93333333 69.93333333 66.86666667 63.03333333 60.16666667 57.83333333
 55.53333333 53.5        52.4        50.5        48.6       ]
[2.24845626 1.96694913 1.45220139 1.73076733 1.09645895 0.85764536
 0.98432154 1.17756812 1.2083046  0.85244746 0.63770422]
[75.36666667 71.76666667 68.36666667 64.6        61.9        59.76666667
 57.93333333 55.33333333 54.16666667 52.6        50.53333333]
[2.20050499 1.66599987 1.62138487 1.65730705 0.65319726 0.97410928
 0.87305339 1.37679176 1.41970263 1.23558353 1.07806411]
[73.93333333 71.46666667 69.43333333 67.43333333 65.76666667 64.06666667
 61.86666667 60.5        58.2        57.56666667 55.93333333 55.13333333
 54.76666667 53.56666667 52.33333333 51.26666667 50.

FileNotFoundError: [Errno 2] No such file or directory: './results/podnet/20230506-2323_cifar_cnn_inc_1/run_0_.json'